-- Create the table anew
create table books (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  author_last text,
  author_first text,
  description text,
  category_id INTEGER REFERENCES categories(id) NOT NULL,
  subcategory_id INTEGER REFERENCES subcategories(id) NOT NULL
);